SELECT TOP (10) [ID_CLI]
      ,[NOME_CLIENTE]
      ,[CPF]
      ,[DATA_NASCIMENTO]
      ,[RENDA_MENSAL]
      ,[PROFISSAO]
      ,[SCORE]
      ,[STATUS_CLI]
      ,[SEXO]
      ,[AREA]
  FROM [TABELA_TESTE].[dbo].[Clientes]
